name: sheryan_paramedic
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.4
  google_maps_flutter: ^2.2.3
  dio: ^5.0.3
  fluttertoast: ^8.2.1
  shared_preferences: ^2.1.0
  flutter_zoom_drawer: ^3.0.4+1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true